# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2

builds:
  - env:
      - "CGO_ENABLED=0"
    goos:
      - "darwin"
      - "linux"
      - "windows"
    goarch:
      - "amd64"
      - "arm64"

aurs:
  - name: "zabbixmon-bin"
    homepage: "https://github.com/nikaro/zabbixmon"
    description: "CLI application to show currents alerts on Zabbix."
    maintainers:
      - "Nicolas Karolak <nicolas at karolak dot fr>"
    license: "GPLv3"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/zabbixmon-bin.git"
    package: |-
      install -Dm755 "./zabbixmon" "${pkgdir}/usr/bin/zabbixmon"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/zabbixmon/LICENSE"

nfpms:
  - package_name: "zabbixmon"
    homepage: "https://github.com/nikaro/zabbixmon"
    description: "CLI application to show currents alerts on Zabbix."
    maintainer: "Nicolas Karolak <nicolas@karolak.fr>"
    license: "GPLv3"
    formats:
      - "apk"
      - "deb"
      - "rpm"
    contents:
      - src: "LICENSE"
        dst: "/usr/share/licenses/zabbixmon/LICENSE"
