# zabbix server authentication
server = "https://zabbix.example.com"
username = "myuser"
password = "mypassword"

# logging levels: debug, info, warning, error
log-level = "warning"

# filter types of alerts
item-types = ["down", "unack", "ack", "unknown"]

# minimum trigger severities: unknown, information, warning, average, high, critical
min-severity = "average"

# refresh data every N seconds
refresh = 60

# enable notifications
notify = false
