version: '3'

set: [errexit, nounset, pipefail]
shopt: [globstar]

includes:
  lint:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/lint.yml
    internal: true
  format:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/format.yml
    internal: true
  go:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/go.yml

env:
  APP: zabbixmon

tasks:
  init:
    desc: Initialize repositry
    cmds:
      - git config core.hooksPath .githooks
      - git config commit.template .gitmessage

  lint:
    desc: Run linters
    cmds:
      - task: lint:default
      - task: go:lint

  format:
    desc: Run formatters
    cmds:
      - task: format:default
      - task: go:format
