name: CD

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release:
    name: Release
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh repo clone ${{ github.repository }} -- --branch "$BRANCH"

      - name: Dry run
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: _changelog.md
          dry_run: true

      - name: Bump
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: _changelog.md

      - name: Setup Go
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: actions/setup-go@main
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod

      - name: Run GoReleaser
        if: env.PREVIOUS_REVISION != env.REVISION
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --clean --release-notes _changelog.md
        env:
          AUR_KEY: ${{ secrets.AUR_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
